import { Match } from "@/types/match";

export const MOCK_MATCHES: Match[] = [
  {
    id: "m1",
    date: "2025-09-14",
    season: "2025-2026",
    ageGroup: "U15",
    opponent: "Fenerbahçe Alt Yapı",
    homeAway: "home",
    scoreHome: 3,
    scoreAway: 1,
    result: "W",
    venue: "Beylerbeyi Sahası",
    notes: "Sezon açılış maçı, güçlü performans.",
    playerStats: [
      { playerId: "3", playerName: "Emre Demir", jerseyNumber: 1, position: "Kaleci", minutesPlayed: 90, goals: 0, assists: 0, yellowCards: 0, redCards: 0, goalsConceded: 1, cleanSheet: false },
      { playerId: "4", playerName: "Can Özkan", jerseyNumber: 4, position: "Defans", minutesPlayed: 90, goals: 0, assists: 0, yellowCards: 1, redCards: 0, goalsConceded: 0, cleanSheet: false },
      { playerId: "2", playerName: "Mehmet Kaya", jerseyNumber: 10, position: "Orta Saha", minutesPlayed: 85, goals: 1, assists: 2, yellowCards: 0, redCards: 0, goalsConceded: 0, cleanSheet: false },
      { playerId: "1", playerName: "Ali Yılmaz", jerseyNumber: 9, position: "Forvet", minutesPlayed: 90, goals: 2, assists: 0, yellowCards: 0, redCards: 0, goalsConceded: 0, cleanSheet: false },
    ],
    createdAt: "2025-09-14",
    updatedAt: "2025-09-14",
  },
  {
    id: "m2",
    date: "2025-09-21",
    season: "2025-2026",
    ageGroup: "U15",
    opponent: "Galatasaray Alt Yapı",
    homeAway: "away",
    scoreHome: 1,
    scoreAway: 1,
    result: "D",
    venue: "Florya Metin Oktay Tesisleri",
    playerStats: [
      { playerId: "3", playerName: "Emre Demir", jerseyNumber: 1, position: "Kaleci", minutesPlayed: 90, goals: 0, assists: 0, yellowCards: 0, redCards: 0, goalsConceded: 1, cleanSheet: false },
      { playerId: "4", playerName: "Can Özkan", jerseyNumber: 4, position: "Defans", minutesPlayed: 90, goals: 0, assists: 1, yellowCards: 0, redCards: 0, goalsConceded: 0, cleanSheet: false },
      { playerId: "2", playerName: "Mehmet Kaya", jerseyNumber: 10, position: "Orta Saha", minutesPlayed: 90, goals: 0, assists: 0, yellowCards: 1, redCards: 0, goalsConceded: 0, cleanSheet: false },
      { playerId: "1", playerName: "Ali Yılmaz", jerseyNumber: 9, position: "Forvet", minutesPlayed: 75, goals: 1, assists: 0, yellowCards: 0, redCards: 0, goalsConceded: 0, cleanSheet: false },
    ],
    createdAt: "2025-09-21",
    updatedAt: "2025-09-21",
  },
  {
    id: "m3",
    date: "2025-09-28",
    season: "2025-2026",
    ageGroup: "U15",
    opponent: "Beşiktaş Alt Yapı",
    homeAway: "home",
    scoreHome: 0,
    scoreAway: 2,
    result: "L",
    venue: "Beylerbeyi Sahası",
    notes: "Zor maç, savunmada hatalar yapıldı.",
    playerStats: [
      { playerId: "3", playerName: "Emre Demir", jerseyNumber: 1, position: "Kaleci", minutesPlayed: 90, goals: 0, assists: 0, yellowCards: 0, redCards: 0, goalsConceded: 2, cleanSheet: false },
      { playerId: "4", playerName: "Can Özkan", jerseyNumber: 4, position: "Defans", minutesPlayed: 90, goals: 0, assists: 0, yellowCards: 1, redCards: 0, goalsConceded: 0, cleanSheet: false },
      { playerId: "2", playerName: "Mehmet Kaya", jerseyNumber: 10, position: "Orta Saha", minutesPlayed: 90, goals: 0, assists: 0, yellowCards: 0, redCards: 0, goalsConceded: 0, cleanSheet: false },
      { playerId: "1", playerName: "Ali Yılmaz", jerseyNumber: 9, position: "Forvet", minutesPlayed: 60, goals: 0, assists: 0, yellowCards: 1, redCards: 0, goalsConceded: 0, cleanSheet: false },
    ],
    createdAt: "2025-09-28",
    updatedAt: "2025-09-28",
  },
  {
    id: "m4",
    date: "2025-10-05",
    season: "2025-2026",
    ageGroup: "U17",
    opponent: "Trabzonspor Alt Yapı",
    homeAway: "home",
    scoreHome: 2,
    scoreAway: 0,
    result: "W",
    venue: "Beylerbeyi Sahası",
    playerStats: [
      { playerId: "5", playerName: "Berk Arslan", jerseyNumber: 11, position: "Forvet", minutesPlayed: 90, goals: 2, assists: 0, yellowCards: 0, redCards: 0, goalsConceded: 0, cleanSheet: false },
    ],
    createdAt: "2025-10-05",
    updatedAt: "2025-10-05",
  },
  {
    id: "m5",
    date: "2025-10-12",
    season: "2025-2026",
    ageGroup: "U19",
    opponent: "Başakşehir Alt Yapı",
    homeAway: "away",
    scoreHome: 1,
    scoreAway: 3,
    result: "L",
    venue: "Başakşehir Fatih Terim Stadı",
    playerStats: [
      { playerId: "6", playerName: "Yusuf Çelik", jerseyNumber: 8, position: "Orta Saha", minutesPlayed: 90, goals: 1, assists: 0, yellowCards: 1, redCards: 0, goalsConceded: 0, cleanSheet: false },
    ],
    createdAt: "2025-10-12",
    updatedAt: "2025-10-12",
  },
  {
    id: "m6",
    date: "2025-10-19",
    season: "2025-2026",
    ageGroup: "U17",
    opponent: "Kasımpaşa Alt Yapı",
    homeAway: "away",
    scoreHome: 3,
    scoreAway: 2,
    result: "W",
    venue: "Kasımpaşa Tesisleri",
    playerStats: [
      { playerId: "5", playerName: "Berk Arslan", jerseyNumber: 11, position: "Forvet", minutesPlayed: 80, goals: 1, assists: 1, yellowCards: 1, redCards: 0, goalsConceded: 0, cleanSheet: false },
    ],
    createdAt: "2025-10-19",
    updatedAt: "2025-10-19",
  },
];
